ImportError: cannot import name AddWin from partially initialized module add_win (most likely due to a circular import) + so I’ll redo the main screen + I don’t like the architecture, I should apply a pattern